<?php
    require_once '../fuerza_aerea/templates/layouts/header.phtml';
    require_once __DIR__ . '/../app/views/categoriaViews.php';
?>

<main>
    <div class="main-listados">
        <h2 class="main-listados-titulo">Categorías</h2>
        <table class="main-listados-tabla">
            <thead>
                <tr>
                    <td>CATEGORÍA</td>
                </tr>
                </thead>
            <tbody>
                <?php foreach($categorias as $categoria): ?>
                    <tr>
                        <td><a href="categoria/<?=$categoria->id?>"><?=$categoria->nombre?></a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</main>

<?php
    require_once '../fuerza_aerea/templates/layouts/footer.phtml';
?>

